//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYWEBAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYTABLE
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Title { get; set; }
        public string Band { get; set; }
        public string Length { get; set; }
    }
}
